name: Flask App Workflow

on:
  # push:
  #   branches:
  #     - dev
  #     - main    
  workflow_dispatch: # Trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    # outputs:
    #   version: ${{ steps.set-version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub 
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Generate and Set Version
      #id: set-version
      run: 
        # Generate version based on the current epoch time
        EPOCH_TIME=$(date +%s)
        VERSION="v${EPOCH_TIME}"
        echo "version=$VERSION" >> "$GITHUB_ENV" 
        echo "Generated version: $VERSION"
    
    - name: Build Docker image
      run: 
        echo "Building the Docker image..."
        docker build -t ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.version }} .
        echo "Build completed on $(date)"
        # Tags the built image for ECR repository
        docker tag ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.version }} ${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.version }}
        echo "Build completed on $(date)"  
      # Prints a timestamp when the build is completed

    - name: Push Docker image
      run: 
        echo "Pushing the Docker image..."
        docker images  # Optionally list images to confirm the image exists
        docker push ${{ secrets.DOCKER_HUB_REGISTRY }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ env.version }}
        echo "Image pushed to Docker Hub with tag: ${{ env.version }}"